name: R-CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 4.x

    - name: Install Dependencies
      run: Rscript -e 'install.packages("testthat")'

    - name: Run Tests
      run: Rscript -e 'testthat::test_dir("tests")'
